language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - composer install -n
  - mysql -u root -e "CREATE USER 'damosansa'@'localhost' IDENTIFIED BY 'damosansa'"
  - mysql -u root -e "CREATE DATABASE dam_o_sansa DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
  - mysql -u root -e "CREATE DATABASE dam_o_sansa_test DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON dam_o_sansa.* TO 'damosansa'@'localhost' WITH GRANT OPTION;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON dam_o_sansa_test.* TO 'damosansa'@'localhost' WITH GRANT OPTION;"
#  - app/console doctrine:migrations:migrate --no-interaction
#  - app/console doctrine:migrations:migrate --env=test --no-interaction

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml -c app

after_script:
  - bin/coveralls -v