homepage:
    path: /acasa
    defaults: { _controller: DamOSansaBundle:Content:home }

partners:
    path: /parteneri
    defaults: { _controller: DamOSansaBundle:Content:partners }

contact:
    path: /contact
    defaults: { _controller: DamOSansaBundle:Content:contact }

therapy:
    path: /terapie/{type}
    defaults: { _controller: DamOSansaBundle:Content:therapy, type: "all" }

dissability:
    path: /dizabilitati/{type}
    defaults: { _controller: DamOSansaBundle:Content:dissability, type: "all" }

default:
    path: /
    defaults: { _controller: DamOSansaBundle:Content:home }