homepage:
    path: /home
    defaults: { _controller: DamOSansaBundle:Content:home }

therapy:
    path: /therapy/{type}
    defaults: { _controller: DamOSansaBundle:Content:therapy, type: "all" }

default:
    path: /
    defaults: { _controller: DamOSansaBundle:Content:home }