homepage:
    path: /home
    defaults: { _controller: DamOSansaBundle:Content:home }

partners:
    path: /partners
    defaults: { _controller: DamOSansaBundle:Content:partners }

therapy:
    path: /therapy/{type}
    defaults: { _controller: DamOSansaBundle:Content:therapy, type: "all" }

dissability:
    path: /dissability/{type}
    defaults: { _controller: DamOSansaBundle:Content:dissability, type: "all" }

default:
    path: /
    defaults: { _controller: DamOSansaBundle:Content:home }